"""
Seed Data for SIH PS 26131 — Maharashtra Crop Surveillance System
Realistic geotagged outbreak reports centered around Maharashtra's key agricultural belts:
1. Pune (Junnar/Ambegaon Tomato Cluster)
2. Nashik (Niphad/Dindori Tomato & Potato Belt)
3. Jalgaon & Vidarbha (Amravati/Wardha Cotton Belts)
"""

from datetime import datetime, timedelta, timezone

def generate_seed_reports():
    now = datetime.now(timezone.utc)
    
    seeds = [
        # Pune Junnar Tomato Belt — Early Blight Hotspot Cluster
        {
            "id": "RPT-MH-2026-0101",
            "crop": "Tomato",
            "disease_id": "tomato_early_blight",
            "disease_name": "Early Blight",
            "confidence": 0.942,
            "latitude": 19.2088,
            "longitude": 73.8765,
            "district": "Pune",
            "taluka": "Junnar",
            "village": "Otur",
            "severity": "high",
            "status": "investigating",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9822X X4501",
            "notes": "Spotted target board lesions on lower leaves after continuous rains.",
            "timestamp": (now - timedelta(hours=4)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0102",
            "crop": "Tomato",
            "disease_id": "tomato_early_blight",
            "disease_name": "Early Blight",
            "confidence": 0.915,
            "latitude": 19.1950,
            "longitude": 73.8890,
            "district": "Pune",
            "taluka": "Junnar",
            "village": "Alephata",
            "severity": "high",
            "status": "investigating",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9823X X1190",
            "notes": "Severe yellowing and dropping of leaves in 2-acre plot.",
            "timestamp": (now - timedelta(hours=7)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0103",
            "crop": "Tomato",
            "disease_id": "tomato_early_blight",
            "disease_name": "Early Blight",
            "confidence": 0.963,
            "latitude": 19.1830,
            "longitude": 73.9120,
            "district": "Pune",
            "taluka": "Junnar",
            "village": "Belnhe",
            "severity": "high",
            "status": "reported",
            "flagged_for_expert": True,
            "farmer_phone_masked": "+91 9765X X8743",
            "notes": "Symptoms spreading quickly across ridge rows.",
            "timestamp": (now - timedelta(hours=11)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0104",
            "crop": "Tomato",
            "disease_id": "tomato_early_blight",
            "disease_name": "Early Blight",
            "confidence": 0.887,
            "latitude": 19.0125,
            "longitude": 73.9560,
            "district": "Pune",
            "taluka": "Ambegaon",
            "village": "Manchar",
            "severity": "high",
            "status": "investigating",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9422X X3045",
            "notes": "Farmer sprayed Mancozeb 3 days ago, awaiting secondary review.",
            "timestamp": (now - timedelta(days=1, hours=2)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0105",
            "crop": "Tomato",
            "disease_id": "tomato_bacterial_spot",
            "disease_name": "Bacterial Spot",
            "confidence": 0.892,
            "latitude": 18.9810,
            "longitude": 73.9210,
            "district": "Pune",
            "taluka": "Khed",
            "village": "Chakan",
            "severity": "medium",
            "status": "contained",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9881X X5520",
            "notes": "Angular greasy spots on foliage; controlled with Streptocycline.",
            "timestamp": (now - timedelta(days=2)).isoformat()
        },

        # Nashik Niphad / Dindori Belt — Late Blight Critical Cluster
        {
            "id": "RPT-MH-2026-0201",
            "crop": "Tomato",
            "disease_id": "tomato_late_blight",
            "disease_name": "Late Blight",
            "confidence": 0.978,
            "latitude": 20.0820,
            "longitude": 74.1250,
            "district": "Nashik",
            "taluka": "Niphad",
            "village": "Pimpalgaon Baswant",
            "severity": "critical",
            "status": "reported",
            "flagged_for_expert": True,
            "farmer_phone_masked": "+91 9922X X9022",
            "notes": "Water-soaked black lesions and rotting fruits after 3 days of dense fog.",
            "timestamp": (now - timedelta(hours=3)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0202",
            "crop": "Tomato",
            "disease_id": "tomato_late_blight",
            "disease_name": "Late Blight",
            "confidence": 0.954,
            "latitude": 20.0950,
            "longitude": 74.1410,
            "district": "Nashik",
            "taluka": "Niphad",
            "village": "Sukene",
            "severity": "critical",
            "status": "investigating",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9850X X6718",
            "notes": "White fungal fuzz visible under wet leaf margins.",
            "timestamp": (now - timedelta(hours=5)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0203",
            "crop": "Potato",
            "disease_id": "potato_late_blight",
            "disease_name": "Late Blight",
            "confidence": 0.961,
            "latitude": 20.1420,
            "longitude": 73.8340,
            "district": "Nashik",
            "taluka": "Dindori",
            "village": "Vani",
            "severity": "critical",
            "status": "investigating",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9730X X1499",
            "notes": "Late blight rotting tuber canopy in early kharif potato.",
            "timestamp": (now - timedelta(hours=9)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0204",
            "crop": "Potato",
            "disease_id": "potato_early_blight",
            "disease_name": "Early Blight",
            "confidence": 0.912,
            "latitude": 20.0150,
            "longitude": 74.0120,
            "district": "Nashik",
            "taluka": "Niphad",
            "village": "Khedgaon",
            "severity": "high",
            "status": "contained",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9821X X7733",
            "notes": "Brown concentric spots; responsive to Mancozeb.",
            "timestamp": (now - timedelta(days=1, hours=8)).isoformat()
        },

        # Amravati & Wardha Vidarbha Belt — Cotton Leaf Curl & Sucking Pest Cluster
        {
            "id": "RPT-MH-2026-0301",
            "crop": "Cotton",
            "disease_id": "cotton_leaf_curl",
            "disease_name": "Leaf Curl / Sucking Pest Damage",
            "confidence": 0.948,
            "latitude": 20.9450,
            "longitude": 77.7850,
            "district": "Amravati",
            "taluka": "Amravati",
            "village": "Walgaon",
            "severity": "critical",
            "status": "investigating",
            "flagged_for_expert": True,
            "farmer_phone_masked": "+91 9604X X8812",
            "notes": "Severe upward leaf cupping and thick veins; high whitefly count.",
            "timestamp": (now - timedelta(hours=6)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0302",
            "crop": "Cotton",
            "disease_id": "cotton_leaf_curl",
            "disease_name": "Leaf Curl / Sucking Pest Damage",
            "confidence": 0.925,
            "latitude": 21.2850,
            "longitude": 78.0120,
            "district": "Amravati",
            "taluka": "Morshi",
            "village": "Nerpingalai",
            "severity": "critical",
            "status": "reported",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9403X X2984",
            "notes": "Heavy pest infestation on Bt Cotton canopy.",
            "timestamp": (now - timedelta(hours=14)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0303",
            "crop": "Cotton",
            "disease_id": "cotton_bacterial_blight",
            "disease_name": "Bacterial Blight (Black Arm)",
            "confidence": 0.938,
            "latitude": 20.7510,
            "longitude": 78.5980,
            "district": "Wardha",
            "taluka": "Wardha",
            "village": "Sewagram",
            "severity": "high",
            "status": "investigating",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9890X X5041",
            "notes": "Black lesions girdling main stems (Black Arm) after gusty rains.",
            "timestamp": (now - timedelta(days=1)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0304",
            "crop": "Cotton",
            "disease_id": "cotton_bacterial_blight",
            "disease_name": "Bacterial Blight (Black Arm)",
            "confidence": 0.905,
            "latitude": 20.5520,
            "longitude": 78.8350,
            "district": "Wardha",
            "taluka": "Hinganghat",
            "village": "Wadner",
            "severity": "high",
            "status": "reported",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9860X X9123",
            "notes": "Square shedding reported in 4 adjacent farms.",
            "timestamp": (now - timedelta(days=1, hours=16)).isoformat()
        },

        # Jalgaon Khandesh Belt — Cotton Blight & Leaf Curl
        {
            "id": "RPT-MH-2026-0401",
            "crop": "Cotton",
            "disease_id": "cotton_bacterial_blight",
            "disease_name": "Bacterial Blight (Black Arm)",
            "confidence": 0.931,
            "latitude": 21.2450,
            "longitude": 75.6980,
            "district": "Jalgaon",
            "taluka": "Yawal",
            "village": "Faizpur",
            "severity": "high",
            "status": "investigating",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9423X X1756",
            "notes": "Angular leaf spots spreading through vein boundaries.",
            "timestamp": (now - timedelta(hours=18)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0402",
            "crop": "Cotton",
            "disease_id": "cotton_leaf_curl",
            "disease_name": "Leaf Curl / Sucking Pest Damage",
            "confidence": 0.917,
            "latitude": 21.3210,
            "longitude": 75.8950,
            "district": "Jalgaon",
            "taluka": "Raver",
            "village": "Savda",
            "severity": "critical",
            "status": "reported",
            "flagged_for_expert": True,
            "farmer_phone_masked": "+91 9763X X3940",
            "notes": "Stunted seedlings with crinkled leaf margins.",
            "timestamp": (now - timedelta(days=1, hours=5)).isoformat()
        },

        # Ahmednagar (Ahilyanagar) Belt — Tomato & Cotton
        {
            "id": "RPT-MH-2026-0501",
            "crop": "Tomato",
            "disease_id": "tomato_early_blight",
            "disease_name": "Early Blight",
            "confidence": 0.928,
            "latitude": 19.5780,
            "longitude": 74.2140,
            "district": "Ahmednagar",
            "taluka": "Sangamner",
            "village": "Talegaon Dighe",
            "severity": "high",
            "status": "investigating",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9822X X7711",
            "notes": "Alternaria spots observed on stake-trained tomatoes.",
            "timestamp": (now - timedelta(hours=22)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0502",
            "crop": "Tomato",
            "disease_id": "tomato_healthy",
            "disease_name": "Healthy Plant",
            "confidence": 0.985,
            "latitude": 19.6450,
            "longitude": 74.4820,
            "district": "Ahmednagar",
            "taluka": "Rahata",
            "village": "Shirdi Rural",
            "severity": "none",
            "status": "resolved",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9921X X4188",
            "notes": "Routine inspection scan; vigorous green canopy.",
            "timestamp": (now - timedelta(days=2, hours=4)).isoformat()
        },

        # Solapur Belt — Potato & Tomato
        {
            "id": "RPT-MH-2026-0601",
            "crop": "Potato",
            "disease_id": "potato_early_blight",
            "disease_name": "Early Blight",
            "confidence": 0.902,
            "latitude": 17.7120,
            "longitude": 75.3120,
            "district": "Solapur",
            "taluka": "Pandharpur",
            "village": "Bhalwani",
            "severity": "high",
            "status": "reported",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9421X X0955",
            "notes": "Lower leaf defoliation after sudden temperature rise.",
            "timestamp": (now - timedelta(days=1, hours=10)).isoformat()
        },
        {
            "id": "RPT-MH-2026-0602",
            "crop": "Tomato",
            "disease_id": "tomato_healthy",
            "disease_name": "Healthy Plant",
            "confidence": 0.976,
            "latitude": 17.6650,
            "longitude": 75.9100,
            "district": "Solapur",
            "taluka": "North Solapur",
            "village": "Kegaon",
            "severity": "none",
            "status": "resolved",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9881X X3267",
            "notes": "Healthy plot checked during KVK demonstration.",
            "timestamp": (now - timedelta(days=3)).isoformat()
        },

        # Chhatrapati Sambhajinagar — Cotton & Tomato
        {
            "id": "RPT-MH-2026-0701",
            "crop": "Cotton",
            "disease_id": "cotton_bacterial_blight",
            "disease_name": "Bacterial Blight (Black Arm)",
            "confidence": 0.919,
            "latitude": 19.7020,
            "longitude": 75.0120,
            "district": "Chhatrapati Sambhaji Nagar",
            "taluka": "Gangapur",
            "village": "Waluj Rural",
            "severity": "high",
            "status": "investigating",
            "flagged_for_expert": False,
            "farmer_phone_masked": "+91 9766X X8840",
            "notes": "Vein-bound angular spots; advisory broadcast initiated.",
            "timestamp": (now - timedelta(hours=16)).isoformat()
        }
    ]
    return seeds
